feat(landing_page): First draft
StatCan/kubeflow-containers-desktop pull request #30
Opened 2020-07-28 16:44 UTC by frazs

First draft of the landing page. The functionality and general concept is there, and if desired I can add on some relatively simple things such as SVG icons, but I am not much of a front end developer so this may warrant being passed up to somebody in UI.

Addresses https://github.com/StatCan/kubeflow-containers/issues/38

2020-07-28 16:47 UTC, frazs commented
https://htmlpreview.github.io/?https://github.com/StatCan/kubeflow-containers-desktop/blob/landingpage/base/resources/landing_page/index.html

2020-07-28 18:48 UTC, frazs commented
Threw in a quick go at icons, which works great locally but is completely messed in that html preview, so I'm going to take a look into that.

2020-07-28 19:02 UTC, frazs commented
Looks to be an issue with the previewer (possibly a caching one - it may be pulling an older version of the css), this works: https://raw.githack.com/StatCan/kubeflow-containers-desktop/landingpage/base/resources/landing_page/index.html

Though my CSS was very fast and loose for a quick proof of concept, with text changed to get things to align better (wrt e.g. centering), so there should still be a better way to set things up with a more explicit structure.

2020-07-31 16:24 UTC, frazs commented
In today's stand-up, @brendangadd said he wanted to go over the HTML for best practices and accessibility before this is pulled in. I'm putting this in Draft until that's done.

For anyone reviewing this, note that one way or another the URLs must be dynamically built (but perhaps it is possible to dynamically build a string that's fed into an `<a href ...>` if that is what is best for e.g. screen readers). This is because of the dynamic workspace base URL component (the part that is `/notebook/namespace/container-name/`). Or at least in my attempts to use relative links, they would attach directly to the kubeflow domain, which wouldn't work -- but perhaps I missed something.

2020-08-05 20:43 UTC, frazs commented
Rebased to sync up with other recent updates. @wg102 is going to take a look.

2020-08-05 20:57 UTC, frazs commented
While there please see if you can fix the "no newline" git warnings (IIRC Saffa had luck just adding a new line at the end) and I'm going to try to figure out why that keeps happening on my end.

2020-08-12 13:18 UTC, wg102 commented
I modified the code to use 'a' elements instead and verified the navigation using tabs.

2020-08-12 17:08 UTC, frazs commented
LGTM. @brendangadd?

2020-08-13 18:46 UTC, brendangadd requested changes
In addition to line comments:
* Run JS through eslint
* Run HTML, CSS, JS through Prettier

2020-08-13 18:46 UTC, brendangadd commented on base/Dockerfile
> +CMD ["/init.sh"]
Keep the trailing new line.

2020-08-13 18:46 UTC, brendangadd commented on base/resources/landing_page/script.js
> +  launcherLinks[i].setAttribute('href',window.location.pathname + launcherLinks[i].getAttribute('data-path'));
Is there a reason we can't just use a relative `href` directly (e.g. `href="relative/path/to/resource"`)?

2020-08-13 18:46 UTC, brendangadd commented on base/resources/landing_page/script.js
> +document.addEventListener("DOMContentLoaded", function() {
**Most** runtime code should wait for this event. Typical pattern:
```js
document.addEventListener("DOMContentLoaded", main);

function main() {
  // Begin runtime initialization, particularly anything
  // that needs DOM.
}
function anotherFunctionAndSoOn() {
  return 'something meaningful';
}
```

2020-08-13 18:46 UTC, brendangadd commented on base/resources/landing_page/script.js
> +        if (isNaN(port) || port < 1 || port > 655335)
Can probably increase lower bound to 1024. Ports less than that are privileged and non-root can't (shouldn't!) be able to open those.

2020-08-13 18:46 UTC, brendangadd commented on base/resources/landing_page/script.js
> +// document.getElementById("page-path-debug").innerHTML = "Page path is: " + window.location.pathname
```suggestion
```

2020-08-13 18:46 UTC, brendangadd commented on base/resources/landing_page/index.html
> +<!DOCTYPE html>
This HTML document is invalid. Run it through https://validator.w3.org

2020-08-13 19:09 UTC, frazs commented on base/resources/landing_page/script.js
> +  launcherLinks[i].setAttribute('href',window.location.pathname + launcherLinks[i].getAttribute('data-path'));
That leads to, for example, `https://kubeflow.covid.cloud.statcan.ca/tools/vscode` which is not in the notebook and does not exist. It needs to include the workspace base url, e.g. `https://kubeflow.covid.cloud.statcan.ca/notebook/namespace/container-name/tools/vscode`.

2020-08-13 20:34 UTC, brendangadd commented on base/resources/landing_page/script.js
> +  launcherLinks[i].setAttribute('href',window.location.pathname + launcherLinks[i].getAttribute('data-path'));
@frazs That stripping of the path should only happen if your `href` uses a leading slash.

2020-08-13 21:41 UTC, frazs commented on base/resources/landing_page/script.js
> +  launcherLinks[i].setAttribute('href',window.location.pathname + launcherLinks[i].getAttribute('data-path'));
Good to know and checks out. Let's move to hrefs with no leading slash then (e.g. `href="tools/vscode"`).

2020-08-14 15:54 UTC, wg102 commented on base/resources/landing_page/script.js
> +document.addEventListener("DOMContentLoaded", function() {
Since relative href are now used, there is no more need of the EventListener.

2020-08-14 17:57 UTC, brendangadd requested changes

2020-08-14 17:57 UTC, brendangadd commented on base/resources/landing_page/index.html
> +    </footer>
This element looks redundant.

2020-08-17 15:28 UTC, brendangadd approved these changes

2020-08-17 15:29 UTC, merged