feat: LibreOffice Calc
StatCan/kubeflow-containers-desktop pull request #41
Opened 2020-08-21 20:01 UTC by frazs

Resolves https://github.com/StatCan/kubeflow-containers-desktop/issues/40

2020-08-21 20:42 UTC, brendangadd requested changes

2020-08-21 20:42 UTC, brendangadd commented on base/Dockerfile
> +RUN add-apt-repository ppa:libreoffice/ppa && \
I'm used to LibreOffice being the core repositories. Why the separate PPA? Required?

2020-08-21 20:42 UTC, brendangadd commented on base/Dockerfile
> +    apt-get install libreoffice && \
Let's just install Calc.

2020-08-21 20:42 UTC, brendangadd commented on base/Dockerfile
> +    chmod +x $HOME/Desktop/libreoffice.desktop && \
As per above, just Calc.

2020-08-24 14:51 UTC, frazs commented on base/Dockerfile
> +RUN add-apt-repository ppa:libreoffice/ppa && \
Depends on what version we want. Separate PPA for 6.4.6.2 (the latest stable version), while the core repositories are at 6.0.7.3. Alternatively, there's a 7.0 available as a collection of debs, but I think that might still be a preview.

2020-08-24 15:20 UTC, frazs commented
No obvious issues dropping down to just libreoffice-calc, so this can be finished as soon as we determine which version to go with. Unless there's an issue with adding a PPA, I'd lean towards the 6.4 as it includes a lot of bugfixes over 6.0 as well as a significantly smoother UI (IMO):

6.0 (in core): 
![image](https://user-images.githubusercontent.com/13685849/91062629-f1d3dd80-e5fa-11ea-92a2-7773fce08dd0.png)

6.4 (in libreoffice/ppa):
![image](https://user-images.githubusercontent.com/13685849/91062709-0a43f800-e5fb-11ea-8f77-99b1cc3f71bf.png)

7.0 was only released about two weeks ago, so we may want to wait until it goes through more testing or a stable release. I haven't tried it out (the installation process is more manual) but can give it a shot if desired.

2020-08-24 15:57 UTC, brendangadd commented
@frazs Avoiding additional PPAs is desirable but, after a bit of research, I think your course of action (adding it) is best. Also, agreed on the clean UI!

Latest stable it is.

2020-08-24 16:42 UTC, frazs commented
Ah, I was wrong on the UI issue. It is not a difference of 6.0 vs 6.4, but a difference of libreoffice-calc alone vs as part of libreoffice. Not sure what the boarder libreoffice package is bringing in to change that...

2020-08-24 17:20 UTC, frazs commented
Sorted it: the missing UI package from the standalone install was `libreoffice-gtk3`.

2020-08-24 20:00 UTC, brendangadd approved these changes

2020-08-24 20:00 UTC, merged